[package]
name = "powdb-cli"
description = "Interactive REPL and CLI for PowDB"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
powdb-storage = { version = "0.1.2", path = "../storage" }
powdb-query = { version = "0.1.2", path = "../query" }
powdb-server = { version = "0.1.2", path = "../server" }
rustyline = "15"
tokio = { version = "1", features = ["rt", "rt-multi-thread", "net", "io-util", "macros"] }
tracing.workspace = true
tracing-subscriber.workspace = true
