// `loader.js` is the package entry point. It exists because `index.js` is
// generated by `napi build` and cannot be hand-edited, so the two things that
// generated file gets wrong for this package are corrected here: its
// "cannot find native binding" message, and the missing error classification
// on errors raised by generated argument coercion.
import { test } from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { createRequire } from "node:module";
import Module from "node:module";

const require = createRequire(import.meta.url);
const HERE = dirname(fileURLToPath(import.meta.url));

/** The `${process.platform}-${process.arch}` name each napi target builds for. */
const PLATFORM_FOR_TARGET = {
  "aarch64-apple-darwin": "darwin-arm64",
  "x86_64-unknown-linux-gnu": "linux-x64-gnu",
  "aarch64-unknown-linux-gnu": "linux-arm64-gnu",
};

// This runs first, while the loader is still uncached: it makes the native
// require fail so the unsupported-platform branch is reachable on a machine
// that does have a binary.
test("a missing native binary names the platforms that have one", () => {
  const loaderPath = require.resolve("../loader.js");
  const originalLoad = Module._load;
  const underlying = new Error("Cannot find module './powdb-embedded.linux-riscv64-gnu.node'");
  Module._load = function patched(request, ...rest) {
    if (request === "./index.js") throw underlying;
    return originalLoad.call(this, request, ...rest);
  };
  let err;
  try {
    require("../loader.js");
    assert.fail("expected the loader to rethrow");
  } catch (thrown) {
    err = thrown;
  } finally {
    Module._load = originalLoad;
    delete require.cache[loaderPath];
  }

  // The generated message blames a known npm bug with optional dependencies.
  // This package ships none, so that advice sends anyone on an unsupported
  // platform to reinstall forever.
  assert.doesNotMatch(err.message, /optional dependenc/i);
  assert.equal(err.code, "unsupported_platform");
  assert.equal(err.cause, underlying);
  assert.match(err.message, /darwin-arm64/);
  assert.match(err.message, /linux-x64-gnu/);
  assert.match(err.message, /linux-arm64-gnu/);
  // It says what to do instead of reinstalling.
  assert.match(err.message, /build the addon from source/);
});

test("the supported-platform list matches the targets the package builds", () => {
  const { SUPPORTED_PLATFORMS } = require("../loader.js");
  const pkg = JSON.parse(readFileSync(join(HERE, "..", "package.json"), "utf8"));
  const expected = pkg.napi.targets.map((target) => {
    const platform = PLATFORM_FOR_TARGET[target];
    assert.ok(platform, `no platform name recorded for napi target ${target}`);
    return platform;
  });
  assert.deepEqual([...SUPPORTED_PLATFORMS].sort(), expected.sort());
  // The list has to include this machine, or nothing else in the suite could
  // have loaded the addon at all.
  assert.ok(SUPPORTED_PLATFORMS.includes(`${process.platform}-${process.arch}`));
});
