// `loader.js` is the package entry point. It exists because `index.js` is
// generated by `napi build` and cannot be hand-edited, so the two things that
// generated file gets wrong for this package are corrected here: its
// "cannot find native binding" message, and the missing error classification
// on errors raised by generated argument coercion.
import { test } from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { createRequire } from "node:module";
import Module from "node:module";

const require = createRequire(import.meta.url);
const HERE = dirname(fileURLToPath(import.meta.url));

/** The `${process.platform}-${process.arch}` name each napi target builds for. */
const PLATFORM_FOR_TARGET = {
  "aarch64-apple-darwin": "darwin-arm64",
  "x86_64-unknown-linux-gnu": "linux-x64-gnu",
  "aarch64-unknown-linux-gnu": "linux-arm64-gnu",
};

// This runs first, while the loader is still uncached: it makes the native
// require fail so the unsupported-platform branch is reachable on a machine
// that does have a binary.
test("a missing native binary names the platforms that have one", () => {
  const loaderPath = require.resolve("../loader.js");
  const originalLoad = Module._load;
  const underlying = new Error("Cannot find module './powdb-embedded.linux-riscv64-gnu.node'");
  Module._load = function patched(request, ...rest) {
    if (request === "./index.js") throw underlying;
    return originalLoad.call(this, request, ...rest);
  };
  let err;
  try {
    require("../loader.js");
    assert.fail("expected the loader to rethrow");
  } catch (thrown) {
    err = thrown;
  } finally {
    Module._load = originalLoad;
    delete require.cache[loaderPath];
  }

  // The generated message blames a known npm bug with optional dependencies.
  // This package ships none, so that advice sends anyone on an unsupported
  // platform to reinstall forever.
  assert.doesNotMatch(err.message, /optional dependenc/i);
  assert.equal(err.code, "unsupported_platform");
  assert.equal(err.cause, underlying);
  assert.match(err.message, /darwin-arm64/);
  assert.match(err.message, /linux-x64-gnu/);
  assert.match(err.message, /linux-arm64-gnu/);
  // It says what to do instead of reinstalling.
  assert.match(err.message, /build the addon from source/);
  // The platform it names is the one a reader compares against that list.
  const { platformKey, SUPPORTED_PLATFORMS } = require("../loader.js");
  const named = err.message.match(/no prebuilt native binary for (\S+)\./);
  assert.ok(named, `the message no longer names a platform: ${err.message}`);
  assert.equal(named[1], platformKey());
  assert.ok(SUPPORTED_PLATFORMS.includes(named[1]));
});

test("the supported-platform list matches the targets the package builds", () => {
  const { SUPPORTED_PLATFORMS } = require("../loader.js");
  const pkg = JSON.parse(readFileSync(join(HERE, "..", "package.json"), "utf8"));
  const expected = pkg.napi.targets.map((target) => {
    const platform = PLATFORM_FOR_TARGET[target];
    assert.ok(platform, `no platform name recorded for napi target ${target}`);
    return platform;
  });
  assert.deepEqual([...SUPPORTED_PLATFORMS].sort(), expected.sort());
});

test("the platform key is in the vocabulary the supported list uses", () => {
  const { platformKey, SUPPORTED_PLATFORMS } = require("../loader.js");

  // `${process.platform}-${process.arch}` is not that vocabulary on Linux. A
  // prebuilt binary there is per-libc, so the names carry a suffix and a bare
  // `linux-x64` matches no entry: a membership test against one is false on
  // every Linux runner, which is every runner this package's CI uses.
  assert.ok(!SUPPORTED_PLATFORMS.includes("linux-x64"));

  assert.equal(platformKey("linux", "x64", false), "linux-x64-gnu");
  assert.equal(platformKey("linux", "x64", true), "linux-x64-musl");
  assert.equal(platformKey("linux", "arm64", false), "linux-arm64-gnu");
  // Only Linux splits on libc; nothing else takes a suffix.
  assert.equal(platformKey("darwin", "arm64"), "darwin-arm64");
  assert.equal(platformKey("win32", "x64"), "win32-x64");

  // Every platform the package ships for has to be a key this produces, or the
  // two sides of the membership test are different vocabularies again.
  for (const supported of SUPPORTED_PLATFORMS) {
    const [platform, arch, libc] = supported.split("-");
    assert.equal(platformKey(platform, arch, libc === "musl"), supported);
  }

  // This machine has a binary, or nothing else in the suite could have loaded
  // the addon at all, so it has to be in the list.
  assert.ok(
    SUPPORTED_PLATFORMS.includes(platformKey()),
    `${platformKey()} is not one of ${SUPPORTED_PLATFORMS.join(", ")}`,
  );
});

test("the .d.ts promise about error classification matches what the loader does", () => {
  // dts-header.d.ts is the contract a TypeScript host reads. It shipped two
  // claims the loader did not keep for static factories, so the claims are
  // parsed out of the header here and checked against the loader's own tables
  // rather than restated in this file.
  const { ERROR_CLASS_BY_CODE, NAPI_COERCION_STATUSES } = require("../loader.js");
  const raw = readFileSync(join(HERE, "..", "dts-header.d.ts"), "utf8");
  // Flatten the doc comment so an assertion matches a sentence rather than a
  // particular line wrapping.
  const header = raw.replace(/^\s*\*/gm, " ").replace(/\s+/g, " ");

  const claim = header.match(
    /Argument coercion in generated binding code raises napi's own status strings \(([^)]*)\)/,
  );
  assert.ok(claim, "the napi-status claim is no longer in dts-header.d.ts");
  const named = [...claim[1].matchAll(/`"([A-Za-z]+)"`/g)].map((m) => m[1]);
  assert.ok(named.length >= 2, `expected the header to name statuses, got ${named}`);
  for (const status of named) {
    assert.ok(
      NAPI_COERCION_STATUSES.includes(status),
      `dts-header.d.ts promises ${status} is rewritten, but the loader does not rewrite it`,
    );
  }

  // "It is absent only on an error whose code the loader does not recognize"
  // is only true if recognition means this table, so the header has to keep
  // saying that and the table has to be reachable from here.
  assert.match(header, /absent only on an error whose code the loader does not recognize/);
  assert.ok(Object.keys(ERROR_CLASS_BY_CODE).length > 0);

  // The header promises this of every entry point, factories included.
  assert.match(header, /static factories included/);
});
