/* auto-generated by NAPI-RS */
/* eslint-disable */

/**
 * Recursively decoded JSON from a `json` result cell. A JSON-internal integer
 * within JS's safe range comes back as a `number`; one outside it (but still
 * within i64) widens to `bigint`, so its exact value survives. The same rule
 * the networked `@zvndev/powdb-client` decoder uses. An integer beyond i64
 * range is the one lossy case (it falls back to a `number`); read the sibling
 * `pj1` bytes on the `json` WireValue for the exact, lossless form there.
 */
export type NativeJson =
  | null
  | boolean
  | number
  | bigint
  | string
  | NativeJson[]
  | { [key: string]: NativeJson }

/**
 * A single lossless typed result cell, mirroring the `@zvndev/powdb-client`
 * `WireValue` union so embedded and networked results present the same tagged
 * shape. `empty` (a missing / absent cell) is distinct from a JSON `null`.
 */
export type WireValue =
  | { type: "empty" }
  | { type: "int"; value: bigint }
  | { type: "float"; value: number }
  | { type: "bool"; value: boolean }
  | { type: "str"; value: string }
  | { type: "datetime"; value: bigint }
  | { type: "uuid"; value: Uint8Array }
  | { type: "bytes"; value: Buffer }
  | { type: "json"; value: NativeJson; pj1: Uint8Array }

/**
 * The result of a string-typed query (`query`, `querySql`, `queryReadonly`).
 *
 * A discriminated union on `kind`, identical to `@zvndev/powdb-client`'s
 * `QueryResult`, so the same code narrows whether it is talking to an embedded
 * database or a server. `kind` is one of exactly four values, and each carries
 * only its own fields:
 *
 * ```ts
 * const r = db.query("User")
 * if (r.kind === "rows") {
 *   // r.rows is string[][] here, not string[][] | undefined
 *   for (const row of r.rows) console.log(row.join(", "))
 * }
 * ```
 *
 * The runtime object is the flat `QueryResultShape` below (every field present,
 * the irrelevant ones `undefined`). This union describes which of them are
 * actually populated for a given `kind`, which the flat shape cannot express:
 * against that shape every field was optional, so reading `r.rows` needed a
 * non-null assertion even after checking `r.kind`.
 */
export type QueryResultJs =
  | { kind: "rows"; columns: string[]; rows: string[][] }
  | { kind: "scalar"; value: string }
  | { kind: "ok"; affected: bigint }
  | { kind: "message"; message: string }

/**
 * The result of a native (typed) query. Same `kind` discriminants as the
 * string-typed `QueryResultJs`; only the cell transport differs (`WireValue`
 * instead of `string`).
 */
export type NativeQueryResult =
  | { kind: "rows"; columns: string[]; rows: WireValue[][] }
  | { kind: "scalar"; value: WireValue }
  | { kind: "ok"; affected: bigint }
  | { kind: "message"; message: string }

/**
 * A positional query parameter. The parameter protocol carries only these five
 * scalar shapes: `number` (integral binds as int, otherwise float), `bigint`
 * (int), `string`, `boolean`, and `null` (PowQL `null`).
 */
export type NativeParam = number | bigint | string | boolean | null
