// Package entry point.
//
// `index.js` is generated by `napi build` and cannot be hand-edited, so the two
// things it gets wrong for this package live here instead:
//
//   1. Its "cannot find native binding" message blames a known npm bug with
//      optional dependencies. This package ships no optional dependencies, so
//      that advice sends anyone on an unsupported platform to reinstall
//      forever while the real cause sits in `cause[0]`. The message below says
//      which platforms have prebuilt binaries.
//
//   2. Errors raised by napi's generated argument coercion carry napi's own
//      status names (`StringExpected`, `ArrayExpected`), not this addon's
//      codes, and no error carries the engine's error class at all. Both are
//      attached here, so `err.code` and `err.errorClass` are uniform across
//      every entry point.

"use strict";

/** Platforms this package ships a prebuilt binary for. */
const SUPPORTED_PLATFORMS = ["darwin-arm64", "linux-x64-gnu", "linux-arm64-gnu"];

/**
 * The stable wire error class (docs/errors.md) each code corresponds to. The
 * numbering is the server's, so `err.errorClass` means the same thing whether a
 * caller is talking to an embedded database or to a server over the wire.
 *
 * Every code the addon can throw is here; `__test__/error-codes.test.mjs`
 * fails when one is missing.
 */
const ERROR_CLASS_BY_CODE = Object.freeze({
  // 0 — unclassified or internal: nothing the caller can act on.
  internal: 0,
  open_failed: 0,
  open_panicked: 0,
  poisoned: 0,
  closed: 0,
  already_open: 0,
  sync_failed: 0,
  // 1 — the statement failed to lex or parse.
  parse_error: 1,
  // 2 — planning or execution failed, including a rejected argument.
  query_failed: 2,
  invalid_argument: 2,
  // 3 — a time budget elapsed.
  timeout: 3,
  // 4 — a memory or size limit was exceeded.
  size_exceeded: 4,
  // 5 — the database is read-only and the statement requires a writer.
  readonly_refused: 5,
  // 8 — a constraint rejected the write.
  constraint_violation: 8,
  // 9 — execution was cancelled cooperatively.
  cancelled: 9,
});

/**
 * napi's own status names for argument-coercion failures, which happen in
 * generated code before any addon logic runs. They describe the same thing the
 * addon calls `invalid_argument`.
 */
const NAPI_COERCION_STATUSES = Object.freeze([
  "ArrayExpected",
  "BigintExpected",
  "BooleanExpected",
  "FunctionExpected",
  "InvalidArg",
  "NumberExpected",
  "ObjectExpected",
  "StringExpected",
]);

/**
 * Whether this process links musl rather than glibc. Node's own report names a
 * glibc runtime version and omits it on musl, so this needs no filesystem
 * probe. Always false off Linux, which has no such split.
 */
function processLinksMusl() {
  if (process.platform !== "linux") return false;
  try {
    return !process.report.getReport().header.glibcVersionRuntime;
  } catch {
    return false;
  }
}

/**
 * A platform's name in the vocabulary {@link SUPPORTED_PLATFORMS} uses.
 *
 * `${process.platform}-${process.arch}` is NOT that vocabulary on Linux: a
 * prebuilt binary there is per-libc, so the names carry a `-gnu` or `-musl`
 * suffix and a bare `linux-x64` matches no entry at all. Comparing the two
 * shapes can only ever be false, which is why the key is built here and not
 * at each call site.
 *
 * The defaults describe this process. Only this process's libc is detectable,
 * so a caller naming some other `platform` passes `musl` itself.
 */
function platformKey(
  platform = process.platform,
  arch = process.arch,
  musl = platform === process.platform && processLinksMusl(),
) {
  if (platform !== "linux") return `${platform}-${arch}`;
  return `${platform}-${arch}-${musl ? "musl" : "gnu"}`;
}

function loadNative() {
  try {
    return require("./index.js");
  } catch (err) {
    const platform = platformKey();
    const error = new Error(
      `@zvndev/powdb-embedded has no prebuilt native binary for ${platform}. ` +
        `Prebuilt binaries are published for ${SUPPORTED_PLATFORMS.join(", ")}. ` +
        `On any other platform, build the addon from source ` +
        `(https://github.com/ZVN-DEV/powdb, bindings/node).`,
    );
    error.code = "unsupported_platform";
    error.cause = err;
    throw error;
  }
}

/** Give `err` this package's `code` and its `errorClass`, in place. */
function classify(err) {
  if (!(err instanceof Error)) return err;
  if (typeof err.code === "string" && NAPI_COERCION_STATUSES.includes(err.code)) {
    err.code = "invalid_argument";
  }
  const errorClass = ERROR_CLASS_BY_CODE[err.code];
  if (errorClass !== undefined && err.errorClass === undefined) {
    Object.defineProperty(err, "errorClass", {
      value: errorClass,
      enumerable: true,
      writable: true,
      configurable: true,
    });
  }
  return err;
}

/**
 * Wrap `fn` so anything it throws (or rejects with) is classified first.
 * Iterating whatever the addon exports keeps this from drifting as methods are
 * added.
 */
function classifying(fn) {
  return function classified(...args) {
    try {
      const out = fn.apply(this, args);
      if (out !== null && typeof out === "object" && typeof out.then === "function") {
        return out.then(undefined, (err) => {
          throw classify(err);
        });
      }
      return out;
    } catch (err) {
      throw classify(err);
    }
  };
}

/**
 * Replace every own function property of `target` with a classifying wrapper.
 * For prototypes, whose methods napi defines as writable. Statics need
 * {@link withClassifiedStatics} instead.
 */
function wrapFunctions(target) {
  if (target === null || typeof target !== "object") return;
  for (const name of Object.getOwnPropertyNames(target)) {
    if (name === "constructor") continue;
    const descriptor = Object.getOwnPropertyDescriptor(target, name);
    if (!descriptor || typeof descriptor.value !== "function" || !descriptor.writable) {
      continue;
    }
    Object.defineProperty(target, name, {
      ...descriptor,
      value: classifying(descriptor.value),
    });
  }
}

/**
 * Return a subclass of `cls` whose static factories classify what they throw.
 *
 * napi defines `#[napi(factory)]` statics as non-writable and
 * non-configurable, so they can be replaced neither in place (`defineProperty`
 * throws) nor through a Proxy (a `get` trap on a read-only, non-configurable
 * property must return the target's own value, or the proxy throws). A
 * subclass owns its statics. The wrappers are written from the class's own
 * property names rather than a list, so a factory added later is covered
 * without touching this file.
 */
function withClassifiedStatics(cls) {
  class Classified extends cls {}
  // A host reads this in a stack trace, and `__test__` asserts on it.
  Object.defineProperty(Classified, "name", { value: cls.name, configurable: true });
  for (const name of Object.getOwnPropertyNames(cls)) {
    if (name === "length" || name === "name" || name === "prototype") continue;
    const descriptor = Object.getOwnPropertyDescriptor(cls, name);
    if (!descriptor || typeof descriptor.value !== "function") continue;
    Object.defineProperty(Classified, name, {
      ...descriptor,
      writable: true,
      configurable: true,
      value: classifying(descriptor.value),
    });
  }
  // The factories hand back instances of the native class, not of this
  // subclass, so `db instanceof Database` has to keep meaning what it meant.
  Object.defineProperty(Classified, Symbol.hasInstance, {
    value: (value) => value instanceof cls,
    configurable: true,
  });
  return Classified;
}

const native = loadNative();
for (const name of Object.getOwnPropertyNames(native)) {
  const exported = native[name];
  // Every export the addon has is a class: instance methods on the prototype,
  // and the four ways to open a database as static factories.
  if (typeof exported !== "function" || !exported.prototype) continue;
  wrapFunctions(exported.prototype);
  native[name] = withClassifiedStatics(exported);
}

module.exports = native;
module.exports.SUPPORTED_PLATFORMS = SUPPORTED_PLATFORMS;
module.exports.platformKey = platformKey;
module.exports.ERROR_CLASS_BY_CODE = ERROR_CLASS_BY_CODE;
module.exports.NAPI_COERCION_STATUSES = NAPI_COERCION_STATUSES;
