[package]
name = "powdb-backup"
description = "Backup, restore, and point-in-time recovery for PowDB"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
readme = "../../README.md"
keywords = ["database", "powdb", "backup", "restore", "pitr"]
categories = ["database", "database-implementations"]
documentation = "https://docs.rs/powdb-backup"

[dependencies]
powdb-storage = { version = "0.18.0", path = "../storage" }
powdb-sync = { version = "0.18.0", path = "../sync" }
serde.workspace = true
serde_json.workspace = true
blake3.workspace = true

[dev-dependencies]
powdb-query = { version = "0.18.0", path = "../query" }

[lints]
workspace = true
