#!/usr/bin/env bash
#
# bench-concurrency.sh: measure how PowDB's single-request cost amplifies under
# concurrent clients, and how the read-only serving tier sidesteps the write
# admission gate.
#
# It seeds a ~50K-row table, then measures p50 latency at concurrency 1 vs
# concurrency 10 for three workloads against a normal read-write server:
#   (a) point read by unique id   (indexed lookup)
#   (b) grouped aggregate         (full scan + group)
#   (c) single-row insert         (write admission gate)
# plus a mixed scenario: one reader's p50 while 9 writers hammer inserts.
# The same read workloads then run against a --readonly server on a restored
# copy, where there is no write gate at all.
#
# Load is generated by N concurrent Node processes using the repo's TypeScript
# client (clients/ts). Node is chosen over spawning powdb-cli per query because
# a persistent client connection isolates query latency from process- and
# handshake-startup cost, which is exactly what we want to measure.
#
# The c10/c1 amplification ratio is the stable, portable signal; absolute
# microseconds vary by machine. Prints a results table at the end.
#
# Usage:
#   ./scripts/bench-concurrency.sh
#   POWDB_BIN=/path/to/target/release ./scripts/bench-concurrency.sh
#
set -euo pipefail

# ── Config ───────────────────────────────────────────────────────────────────
SEED_ROWS=50000
CONCURRENCY_HI=10
READ_ITERS=1500        # per client, point read
READ_WARMUP=100
AGG_ITERS=120          # per client, grouped aggregate (each is a full scan)
AGG_WARMUP=15
INS_ITERS=150          # per client, single-row insert (fsync-bound under Full)
INS_WARMUP=20
RUW_ITERS=800          # measured reader iterations under write contention
RUW_WARMUP=100
PORT_RW=5611
PORT_RO=5612

# ── Paths ────────────────────────────────────────────────────────────────────
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
TS_CLIENT="$REPO_ROOT/clients/ts/dist/index.js"
WORK="$(mktemp -d "${TMPDIR:-/tmp}/powdb-bench-concurrency.XXXXXX")"
export POWDB_TS_CLIENT="$TS_CLIENT"

# ── Prerequisites ────────────────────────────────────────────────────────────
if ! command -v node >/dev/null 2>&1; then
  echo "error: node is required (the load generator uses the repo's TS client)" >&2
  exit 1
fi
if [ ! -f "$TS_CLIENT" ]; then
  echo "error: TS client not built at $TS_CLIENT" >&2
  echo "       build it with: (cd clients/ts && pnpm install && pnpm build)" >&2
  exit 1
fi

# ── Binaries (backup/restore are powdb-cli subcommands; no powdb-backup bin) ──
if [ -n "${POWDB_BIN:-}" ]; then
  BIN="$POWDB_BIN"
else
  echo "=== Building powdb-cli and powdb-server (release) ==="
  cargo build --release -p powdb-cli -p powdb-server --manifest-path "$REPO_ROOT/Cargo.toml"
  BIN="$REPO_ROOT/target/release"
fi
PC="$BIN/powdb-cli"
PS="$BIN/powdb-server"
for b in "$PC" "$PS"; do
  [ -x "$b" ] || { echo "error: missing binary: $b" >&2; exit 1; }
done

# ── Process + cleanup management ─────────────────────────────────────────────
SERVER_PIDS=()
cleanup() {
  local pid
  for pid in "${SERVER_PIDS[@]:-}"; do [ -n "$pid" ] && kill "$pid" 2>/dev/null || true; done
  for pid in "${SERVER_PIDS[@]:-}"; do [ -n "$pid" ] && wait "$pid" 2>/dev/null || true; done
  rm -rf "$WORK"
}
trap cleanup EXIT INT TERM

wait_for_port() {
  local port="$1"
  for _ in $(seq 1 100); do
    if (exec 3<>"/dev/tcp/127.0.0.1/$port") 2>/dev/null; then
      exec 3<&- 3>&- || true
      return 0
    fi
    sleep 0.1
  done
  return 1
}

# ── Load generator (embedded; written to the work dir at runtime) ────────────
CLIENT="$WORK/bench-client.mjs"
cat > "$CLIENT" <<'MJS'
const { Client } = await import(process.env.POWDB_TS_CLIENT);
import { writeFileSync } from "node:fs";

function arg(name, def) {
  const i = process.argv.indexOf(`--${name}`);
  return i >= 0 && i + 1 < process.argv.length ? process.argv[i + 1] : def;
}
const host = arg("host", "127.0.0.1");
const port = Number(arg("port", "5611"));
const workload = arg("workload", "point_read");
const iters = Number(arg("iters", "1500"));
const warmup = Number(arg("warmup", "100"));
const idbound = Number(arg("idbound", "50000"));
const out = arg("out", "/dev/stdout");

const KINDS = ["click", "view", "purchase", "signup", "scroll"];

function makeQuery() {
  if (workload === "point_read") {
    const id = 1 + Math.floor(Math.random() * idbound);
    return `Event filter .id = ${id} { .id, .user_id, .kind, .amount }`;
  }
  if (workload === "grouped_agg") {
    return "Event group .kind { .kind, n: count(.kind), total: sum(.amount) }";
  }
  if (workload === "insert") {
    const u = Math.floor(Math.random() * 997);
    const k = KINDS[Math.floor(Math.random() * KINDS.length)];
    const a = Math.floor(Math.random() * 500);
    return `insert Event { user_id := ${u}, kind := "${k}", amount := ${a} }`;
  }
  throw new Error(`unknown workload ${workload}`);
}

const client = await Client.connect({ host, port });
const samples = [];
const total = iters + warmup;
for (let n = 0; n < total; n++) {
  const q = makeQuery();
  const t0 = process.hrtime.bigint();
  try {
    await client.query(q);
  } catch (err) {
    // A writer killed mid-flight (mixed scenario) may see a closed socket;
    // stop cleanly and report whatever we have.
    break;
  }
  const t1 = process.hrtime.bigint();
  if (n >= warmup) samples.push(Number(t1 - t0) / 1000); // microseconds
}
await client.close().catch(() => {});
writeFileSync(out, samples.map((x) => x.toFixed(1)).join("\n") + "\n");
MJS

# median() reads microsecond samples on stdin, prints the p50 as an integer.
median() { sort -n | awk '{a[NR]=$1} END{ if(NR==0){print 0} else {printf "%.0f\n", a[int((NR+1)/2)]} }'; }

# measure <port> <workload> <concurrency> <iters> <warmup> -> prints p50 (us)
measure() {
  local port="$1" wl="$2" c="$3" iters="$4" warmup="$5"
  local d; d="$(mktemp -d "$WORK/m.XXXXXX")"
  local pids=() k
  for k in $(seq 1 "$c"); do
    node "$CLIENT" --port "$port" --workload "$wl" --iters "$iters" \
      --warmup "$warmup" --idbound "$SEED_ROWS" --out "$d/$k.txt" &
    pids+=("$!")
  done
  local p
  for p in "${pids[@]}"; do wait "$p"; done
  cat "$d"/*.txt | median
  rm -rf "$d"
}

# read_under_write <port> <writers> -> prints the reader's p50 (us) while
# `writers` insert clients hammer the same server concurrently.
read_under_write() {
  local port="$1" writers="$2"
  local d; d="$(mktemp -d "$WORK/ruw.XXXXXX")"
  local wpids=() k
  for k in $(seq 1 "$writers"); do
    node "$CLIENT" --port "$port" --workload insert --iters 100000 \
      --warmup 0 --out "$d/w$k.txt" &
    wpids+=("$!")
  done
  # Measured reader runs to completion against the contended server.
  node "$CLIENT" --port "$port" --workload point_read --iters "$RUW_ITERS" \
    --warmup "$RUW_WARMUP" --idbound "$SEED_ROWS" --out "$d/r.txt"
  local p
  for p in "${wpids[@]}"; do kill "$p" 2>/dev/null || true; done
  for p in "${wpids[@]}"; do wait "$p" 2>/dev/null || true; done
  median < "$d/r.txt"
  rm -rf "$d"
}

ratio() { awk -v a="$1" -v b="$2" 'BEGIN{ if(a==0){print "n/a"} else {printf "%.2f", b/a} }'; }

# ── 1. Seed the primary (~50K rows, one transaction) ─────────────────────────
echo "=== Seeding ${SEED_ROWS} rows ==="
PRIMARY="$WORK/primary"
SEED="$WORK/seed.powql"
awk -v n="$SEED_ROWS" 'BEGIN{
  print "type Event { unique auto id: int, required user_id: int, required kind: str, required amount: int };";
  split("click view purchase signup scroll", K, " ");
  print "begin;";
  for (i = 1; i <= n; i++) {
    printf "insert Event { user_id := %d, kind := \"%s\", amount := %d };\n", (i % 997), K[(i % 5) + 1], (i % 500);
  }
  print "commit";
}' > "$SEED"
"$PC" --data-dir "$PRIMARY" --exec-file "$SEED" >/dev/null
seeded="$("$PC" --data-dir "$PRIMARY" --exec 'count(Event)')"
echo "seeded rows: $seeded"

# ── 2. Restore a read-only copy from a backup of the fresh primary ───────────
echo "=== Backup + restore a read-only serving copy ==="
"$PC" --data-dir "$PRIMARY" backup "$WORK/snap" >/dev/null
"$PC" restore "$WORK/snap" "$WORK/ro-copy" >/dev/null

# ── 3. Start both servers (read-write primary, read-only copy) ───────────────
echo "=== Starting servers (rw:$PORT_RW  ro:$PORT_RO) ==="
"$PS" --data-dir "$PRIMARY" --port "$PORT_RW" >"$WORK/rw.log" 2>&1 &
SERVER_PIDS+=("$!")
"$PS" --readonly --data-dir "$WORK/ro-copy" --port "$PORT_RO" >"$WORK/ro.log" 2>&1 &
SERVER_PIDS+=("$!")
wait_for_port "$PORT_RW" || { echo "rw server failed to start"; cat "$WORK/rw.log"; exit 1; }
wait_for_port "$PORT_RO" || { echo "ro server failed to start"; cat "$WORK/ro.log"; exit 1; }

# ── 4. Measure ───────────────────────────────────────────────────────────────
echo "=== Measuring (this takes a couple of minutes) ==="

echo "-- read-write server: point_read --"
RW_PR_C1="$(measure "$PORT_RW" point_read 1 "$READ_ITERS" "$READ_WARMUP")"
RW_PR_CN="$(measure "$PORT_RW" point_read "$CONCURRENCY_HI" "$READ_ITERS" "$READ_WARMUP")"

echo "-- read-write server: grouped_agg --"
RW_AG_C1="$(measure "$PORT_RW" grouped_agg 1 "$AGG_ITERS" "$AGG_WARMUP")"
RW_AG_CN="$(measure "$PORT_RW" grouped_agg "$CONCURRENCY_HI" "$AGG_ITERS" "$AGG_WARMUP")"

echo "-- read-only server: point_read --"
RO_PR_C1="$(measure "$PORT_RO" point_read 1 "$READ_ITERS" "$READ_WARMUP")"
RO_PR_CN="$(measure "$PORT_RO" point_read "$CONCURRENCY_HI" "$READ_ITERS" "$READ_WARMUP")"

echo "-- read-only server: grouped_agg --"
RO_AG_C1="$(measure "$PORT_RO" grouped_agg 1 "$AGG_ITERS" "$AGG_WARMUP")"
RO_AG_CN="$(measure "$PORT_RO" grouped_agg "$CONCURRENCY_HI" "$AGG_ITERS" "$AGG_WARMUP")"

echo "-- read-write server: insert (mutates the primary) --"
RW_IN_C1="$(measure "$PORT_RW" insert 1 "$INS_ITERS" "$INS_WARMUP")"
RW_IN_CN="$(measure "$PORT_RW" insert "$CONCURRENCY_HI" "$INS_ITERS" "$INS_WARMUP")"

echo "-- read-write server: point_read under 9 concurrent writers --"
RW_RUW="$(read_under_write "$PORT_RW" 9)"

# ── 5. Report ────────────────────────────────────────────────────────────────
echo ""
echo "================ RESULTS (p50, microseconds) ================"
printf '%-28s %8s %8s %8s\n' "workload (server)" "c1" "c$CONCURRENCY_HI" "c$CONCURRENCY_HI/c1"
printf '%-28s %8s %8s %8s\n' "----------------------------" "--------" "--------" "--------"
printf '%-28s %8s %8s %8s\n' "point_read (read-write)"  "$RW_PR_C1" "$RW_PR_CN" "$(ratio "$RW_PR_C1" "$RW_PR_CN")"
printf '%-28s %8s %8s %8s\n' "grouped_agg (read-write)" "$RW_AG_C1" "$RW_AG_CN" "$(ratio "$RW_AG_C1" "$RW_AG_CN")"
printf '%-28s %8s %8s %8s\n' "insert (read-write)"      "$RW_IN_C1" "$RW_IN_CN" "$(ratio "$RW_IN_C1" "$RW_IN_CN")"
printf '%-28s %8s %8s %8s\n' "point_read (read-only)"   "$RO_PR_C1" "$RO_PR_CN" "$(ratio "$RO_PR_C1" "$RO_PR_CN")"
printf '%-28s %8s %8s %8s\n' "grouped_agg (read-only)"  "$RO_AG_C1" "$RO_AG_CN" "$(ratio "$RO_AG_C1" "$RO_AG_CN")"
echo "------------------------------------------------------------"
printf 'mixed: point_read p50 with 9 concurrent writers = %s us (vs %s us solo, %sx)\n' \
  "$RW_RUW" "$RW_PR_C1" "$(ratio "$RW_PR_C1" "$RW_RUW")"
echo "============================================================"
echo ""
echo "The c$CONCURRENCY_HI/c1 ratio is the stable signal; absolute microseconds"
echo "vary by machine. Reproduce with: ./scripts/bench-concurrency.sh"
